name: Build Fortran, test it, and optionally publish test outputs

on:
  push:
    branches:
      - amica-python
  pull_request:
    branches:
      - amica-python
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v5

      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: latest
      
      - name: Install dependencies needed for compilation
        run: |
          sudo apt-get update
          sudo apt-get install -y make \
            libblas-dev liblapack-dev \
            openmpi-bin libopenmpi-dev
      
      - name: Build Fortran program
        run: |
          make
      
      - name: Download test data
        run: |
          curl -L -o eeglab_data.fdt https://github.com/sccn/eeglab/raw/develop/sample_data/eeglab_data.fdt
          curl -L -o eeglab_data.set https://github.com/sccn/eeglab/raw/develop/sample_data/eeglab_data.set
          ls -lh eeglab_data.*
      
      - name: Run test dataset
        run: |
          mkdir amicaout_test
          ./amica15ub_test ./amicadefs_test.param
